apiVersion: apps/v1
kind: Deployment
metadata:
  name: settlemate-be
spec:
  replicas: 2
  selector:
    matchLabels:
      app: settlemate-be
  template:
    metadata:
      labels:
        app: settlemate-be
        tags.datadoghq.com/service: settlemate-be
    spec:
      containers:
        - name: api
          image: ghcr.io/settlemate-labs/settlemate-be:develop
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: settlemate-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: settlemate-be
spec:
  selector:
    app: settlemate-be
  ports:
    - port: 8080
      targetPort: 8080
